export const categoryMap = {
  FWC: "🏆 FIFA",
  CC: "🥤 Coca",
  CZE: "🇨🇿 República Tcheca",
  HAI: "🇭🇹 Haiti",
  PAR: "🇵🇾 Paraguai",
  GER: "🇩🇪 Alemanha",
  TUN: "🇹🇳 Tunísia",
  FRA: "🇫🇷 França",
  NOR: "🇳🇴 Noruega",
  ARG: "🇦🇷 Argentina",
  CRO: "🇭🇷 Croácia",
  MEX: "🇲🇽 México",
  RSA: "🇿🇦 África do Sul",
  KOR: "🇰🇷 Coreia do Sul",
  CAN: "🇨🇦 Canadá",
  BIH: "🇧🇦 Bósnia e Herzegovina",
  QAT: "🇶🇦 Catar",
  SUI: "🇨🇭 Suíça",
  MAR: "🇲🇦 Marrocos",
  SCO: "🏴 Escócia",
  USA: "🇺🇸 Estados Unidos",
  AUS: "🇦🇺 Austrália",
  TUR: "🇹🇷 Turquia",
  CUW: "🇨🇼 Curaçao",
  CIV: "🇨🇮 Costa do Marfim",
  ECU: "🇪🇨 Equador",
  NED: "🇳🇱 Holanda",
  JPN: "🇯🇵 Japão",
  SWE: "🇸🇪 Suécia",
  BEL: "🇧🇪 Bélgica",
  EGY: "🇪🇬 Egito",
  IRN: "🇮🇷 Irã",
  NZL: "🇳🇿 Nova Zelândia",
  ESP: "🇪🇸 Espanha",
  CPV: "🇨🇻 Cabo Verde",
  KSA: "🇸🇦 Arábia Saudita",
  URU: "🇺🇾 Uruguai",
  SEN: "🇸🇳 Senegal",
  ALG: "🇩🇿 Argélia",
  AUT: "🇦🇹 Áustria",
  JOR: "🇯🇴 Jordânia",
  POR: "🇵🇹 Portugal",
  COD: "🇨🇩 Congo RD",
  UZB: "🇺🇿 Uzbequistão",
  COL: "🇨🇴 Colômbia",
  ENG: "🏴 Inglaterra",
  GHA: "🇬🇭 Gana",
  PAN: "🇵🇦 Panamá",
  BRA: "🇧🇷 Brasil",
  ITA: "🇮🇹 Itália",
  CHI: "🇨🇱 Chile",
  PER: "🇵🇪 Peru",
  VEN: "🇻🇪 Venezuela",
  BOL: "🇧🇴 Bolívia",
  WAL: "🏴 País de Gales",
  POL: "🇵🇱 Polônia",
  SRB: "🇷🇸 Sérvia",
  CMR: "🇨🇲 Camarões",
  NGA: "🇳🇬 Nigéria",
  MLI: "🇲🇱 Mali",
  BFA: "🇧🇫 Burkina Faso",
  HON: "🇭🇳 Honduras",
  CRC: "🇨🇷 Costa Rica",
  SLV: "🇸🇻 El Salvador",
  JAM: "🇯🇲 Jamaica",
  IRQ: "🇮🇶 Iraque",
  UAE: "🇦🇪 Emirados Árabes",
  OMA: "🇴🇲 Omã",
  CHN: "🇨🇳 China",
  SYR: "🇸🇾 Síria",
  BHR: "🇧🇭 Bahrein",
  SDN: "🇸🇩 Sudão",
  GUI: "🇬🇳 Guiné",
  GAB: "🇬🇦 Gabão",
  ZAM: "🇿🇲 Zâmbia",
  UGA: "🇺🇬 Uganda",
  ROU: "🇷🇴 Romênia",
  UKR: "🇺🇦 Ucrânia",
  SVK: "🇸🇰 Eslováquia",
  HUN: "🇭🇺 Hungria",
  GRE: "🇬🇷 Grécia",
  ISL: "🇮🇸 Islândia",
  IRL: "🇮🇪 Irlanda",
  NIR: "🏴 Irlanda do Norte",
  FIN: "🇫🇮 Finlândia",
  ALB: "🇦🇱 Albânia",
  MKD: "🇲🇰 Macedônia do Norte",
  SVN: "🇸🇮 Eslovênia",
  MNE: "🇲🇪 Montenegro",
  BUL: "🇧🇬 Bulgária",
  ARM: "🇦🇲 Armênia",
  GEO: "🇬🇪 Geórgia",
  ISR: "🇮🇱 Israel",
  LBN: "🇱🇧 Líbano",
  VIE: "🇻🇳 Vietnã",
  THA: "🇹🇭 Tailândia",
  IDN: "🇮🇩 Indonésia",
  MAS: "🇲🇾 Malásia",
  PRK: "🇰🇵 Coreia do Norte",
  IND: "🇮🇳 Índia",
  PHI: "🇵🇭 Filipinas",
  TPE: "🇹🇼 Taipé Chinês",
  HKG: "🇭🇰 Hong Kong",
  MAC: "🇲🇴 Macau",
  SIN: "🇸🇬 Singapura",
  BRU: "🇧🇳 Brunei",
  TLS: "🇹🇱 Timor-Leste",
  MYA: "🇲🇲 Mianmar",
  CAM: "🇰🇭 Camboja",
  LAO: "🇱🇦 Laos",
  BAN: "🇧🇩 Bangladesh",
  MDV: "🇲🇻 Maldivas",
  NEP: "🇳🇵 Nepal",
  BHU: "🇧🇹 Butão",
  SRI: "🇱🇰 Sri Lanka",
  PAK: "🇵🇰 Paquistão",
  AFG: "🇦🇫 Afeganistão",
  TJK: "🇹🇯 Tajiquistão",
  KGZ: "🇰🇬 Quirguistão",
  TKM: "🇹🇲 Turcomenistão",
  KAZ: "🇰🇿 Cazaquistão"
}

export function getCategoryName(category) {
  return categoryMap[category] || category;
}

export const albumOrder = [
  'special',
  'FWC',
  'MEX',
  'RSA',
  'KOR',
  'CZE',
  'CAN',
  'BIH',
  'QAT',
  'SUI',
  'BRA',
  'MAR',
  'HAI',
  'SCO',
  'USA',
  'PAR',
  'AUS',
  'TUR',
  'GER',
  'CUW',
  'CIV',
  'ECU',
  'NED',
  'JPN',
  'SWE',
  'TUN',
  'BEL',
  'EGY',
  'IRN',
  'NZL',
  'ESP',
  'CPV',
  'KSA',
  'URU',
  'FRA',
  'SEN',
  'IRQ',
  'NOR',
  'ARG',
  'ALG',
  'AUT',
  'JOR',
  'POR',
  'COD',
  'UZB',
  'COL',
  'ENG',
  'CRO',
  'GHA',
  'PAN',
  'COKE'
];
